# Generated by Django 3.2.19 on 2023-06-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='measurment_unit',
        ),
    ]
